name: cqlsh
base: core22
version: "5.0.5"
summary: Command-line client for running CQL commands on a cassandra cluster
description: |
  cqlsh is a Python-based command-line client for running CQL commands on a cassandra cluster.

  Normally it's packaged as part of the full Apache Cassandra™ installation. This snap repackages it into a standalone Python package for lighter-weight installs.

grade: stable
confinement: strict
license: Apache-2.0
website: https://github.com/maxiberta/cqlsh-snap
source-code: https://github.com/jeffwidman/cqlsh
compression: lzo

apps:
  cqlsh:
    command: bin/cqlsh
    environment:
      PYTHONPATH: $PYTHONPATH:$SNAP/lib/python2.7/site-packages
    plugs: [network]

parts:
  cqlsh:
    plugin: python
    build-environment:
    - PARTS_PYTHON_INTERPRETER: python2
    source: .
    override-build: |
      craftctl default
      find "${CRAFT_PART_INSTALL}/bin/" -type f -executable -print0 | xargs -0 \
        sed -i "1 s|^#\\!${CRAFT_PART_INSTALL}/bin/python.*$|#\\!/usr/bin/env ${PARTS_PYTHON_INTERPRETER}|"
    build-packages:
      - python-six
      - python2-pip-whl
      - python2-setuptools-whl
      - virtualenv
    python-packages:
      - cassandra-driver < 3.27
      - cqlsh == 5.0.5
      - futures
    stage-packages:
      - python2
